export const gallerypics = [
    {img_src:'./img/photo_gallery/20221008_GWINPhoto-0401.jpg'},
    {img_src: './img/photo_gallery/20221008_GWINPhoto-1587.jpg'},
    {img_src: './img/photo_gallery/20221008_GWINPhoto-3841.jpg'},
    {img_src: './img/photo_gallery/20221008_GWINPhoto-4054.jpg'},
    {img_src: './img/photo_gallery/20221008_GWINPhoto-4953.jpg'},
    {img_src: './img/photo_gallery/20221008_GWINPhoto-5208.jpg'},
    {img_src: './img/photo_gallery/20221008_GWINPhoto-6049.jpg'},
    {img_src: './img/photo_gallery/20221008_GWINPhoto-7373.jpg'},
    {img_src: './img/photo_gallery/20221106_JHG_0055.jpg'},
    {img_src: './img/photo_gallery/Kerri_MICL2022_PTap_Grit-84.jpg'},
    {img_src: './img/photo_gallery/Kerri_MICL2022_PTap_prerides-36.jpg'},
    {img_src: './img/photo_gallery/Kerri_MICL2022_PTap_Wave2-16.jpg'},
    {img_src: './img/photo_gallery/Kerri_MICL2022_PTap_Wave3-2.jpg'},
    {img_src: './img/photo_gallery/Kerri_MICL2022_PTap_Wave3-19.jpg'},
    {img_src: './img/photo_gallery/Kerri_MICL2022_PTap_Wave3-605.jpg'},
    {img_src: './img/photo_gallery/Kerri_MICL2022_PTap_Wave4-520.jpg'},
    {img_src: './img/photo_gallery/KerriAnn Fairhill Wave 3-71.jpg'},
    {img_src: './img/photo_gallery/KerriAnn Fairhill Wave 3-79.jpg'},
    {img_src: './img/photo_gallery/KerriAnn Fairhill Wave 4-327.jpg'},
    {img_src: './img/photo_gallery/KerriAnn_Rivers Edge_2022-11.jpg'},
    {img_src: './img/photo_gallery/KerriAnn_Rivers Edge_2022-84.jpg'},
    {img_src: './img/photo_gallery/KHOPSHOOTS_HD_14.jpg'},
    {img_src: './img/photo_gallery/KHOPSHOOTS_HD_17.jpg'},
    {img_src: './img/photo_gallery/KHOPSHOOTS_HD_68.jpg'},
    {img_src: './img/photo_gallery/KHOPSHOOTS_HD_161.jpg'},
    {img_src: './img/photo_gallery/KHOPSHOOTS_HD_193.jpg'},
    {img_src: './img/photo_gallery/KHOPSHOOTS_HD_214.jpg'},
    {img_src: './img/photo_gallery/KHOPSHOOTS_HD_235.jpg'},
    {img_src: './img/photo_gallery/KHOPSHOOTS_HD_290.jpg'},
    {img_src: './img/photo_gallery/KHOPSHOOTS_HD_302.jpg'},
    {img_src: './img/photo_gallery/KHOPSHOOTS_HD_365.jpg'}
];